# Librairie `numpy`

<div class="alert alert-block alert-danger">
    Si vous utilisez ce notebook via mybinder, pensez à télécharger votre fichier à la fin de la séance afin de conserver une trace de votre travail !
</div>

## Création/manipulation de tableaux

- Créer un vecteur contenant les nombres entiers de 0 à 9 puis n'afficher que les valeurs paires de ce vecteur. Remplacer ensuite ces valeurs paires par -1.

In [1]:
import numpy as np

v = np.arange(0, 10)
v[v % 2 == 1] = -1
v

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

- Créer un vecteur de 20 valeurs flottantes réparties uniformément entre 1 et 50. À l'aide de la fonction `where` de `numpy`, remplacer les valeurs inférieures à 10 par 10 et celle supérieure à 30 par 30.

In [2]:
v = np.random.rand(20) * 50
# v = np.random.uniform(1, 50, 20)
v = np.where(v < 10, 10, np.where(v > 30, 30, v))
v

array([19.87946644, 30.        , 24.32723261, 30.        , 30.        ,
       24.8401172 , 26.07445221, 24.59720805, 20.7934834 , 22.95513771,
       10.6169086 , 12.96725926, 18.0177921 , 25.77778442, 22.32043914,
       26.24181276, 30.        , 16.53115279, 22.04935484, 30.        ])

- Créer les matrices suivantes en respectant le type et en 3 opérations maximum

    \begin{align*}
      \begin{bmatrix}
        1&1&1&1\\
        1&1&1&1\\
        1&1&1&2\\
        1&6&1&1\\
      \end{bmatrix}&\qquad
      \begin{bmatrix}
        0.& 0.& 0.& 0.& 0.\\
        2.& 0.& 0.& 0.& 0.\\
        0.& 3.& 0.& 0.& 0.\\
        0.& 0.& 4.& 0.& 0.\\
        0.& 0.& 0.& 5.& 0.\\
        0.& 0.& 0.& 0.& 6.\\
      \end{bmatrix}
    \end{align*}

    Dans le second cas, on pourra s'aider de la méthode `diag`

In [3]:
M = np.ones((4, 4))
M[2, 3] = 2
M[3, 1] = 6
M

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 2.],
       [1., 6., 1., 1.]])

In [4]:
M = np.diag([2, 3, 4, 5, 6], k=-1)
M = M[:, :5]
M

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

- En utilisant la méthode `tile`, reproduire la matrice suivante à l'aide d'une seule commande

$$
    \begin{bmatrix}
        4& 3& 4& 3& 4& 3\\
        2& 1& 2& 1& 2& 1\\
        4& 3& 4& 3& 4& 3\\
        2& 1& 2& 1& 2& 1\\
    \end{bmatrix}
$$

In [5]:
M = np.tile([[4, 3], [2, 1]], (2, 3))
M

array([[4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1]])

---

## Fonctions universelles

- Créer un tableau à une dimension contenant 1 million de valeurs entières aléatoirement réparties entre 1 et 100

In [6]:
v = np.random.randint(1, 100, 1000000)

- Créer une fonction `inverse` qui retournera un second tableau résultat de l'opération d'inversion ($1/x$) du premier tableau

In [7]:
def inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

- À l'aide de la fonction intégrée `%timeit`, estimer le temps moyen nécessaire à l'exécution de la fonction `inverse`

In [8]:
%timeit inverse(v)

1.33 s ± 68.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


- Estimer ce même temps d'exécution, en utilisant l'opérateur division

In [9]:
%timeit 1/v

1.44 ms ± 66.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


---

## Sale temps sur Seattle

- Télécharger le fichier [`seattle2014.csv`](https://raw.githubusercontent.com/xgarrido/master_python_teaching/master/td/data/seattle2014.csv) qui contient pour chaque jour de l'année 2014 (colonne 1), la hauteur des précipitations exprimé en dixième de millimètres (colonne 2) ainsi que les températures maximale (colonne 3) et minimale (colonne 4), exprimées en dixième de degrés Celsius, à Seattle.

In [10]:
data = np.loadtxt("data/seattle2014.csv", delimiter=",")

day = data[:, 0]
prcp = data[:, 1] / 100  # cm
Tmax = data[:, 2] / 10  # °C
Tmin = data[:, 3] / 10  # °C

- Charger l'ensemble des données dans un tableau `numpy` en prenant bien garde au caractère délimitant chaque champ puis, après avoir converti la hauteur des précipitations en centimètres et les températures en degré Celsius, calculer les valeurs suivantes sur chacune des données du fichier (hauteur des précipitations, $T_\text{min}$ et $T_\text{max}$) :

  1. moyenne, médiane et écart type
  2. valeurs minimale et maximale
  3. les quantiles à 25% et 75%

In [11]:
def print_report(prcp, Tmin, Tmax):
    print("Hauteur des précipitations:")
    print("  valeur moyenne = {:.2f} cm".format(np.mean(prcp)))
    print("  valeur médiane = {:.2f} cm".format(np.median(prcp)))
    print("      écart type = {:.2f} cm".format(np.std(prcp)))
    print("     valeur min. = {:.2f} cm".format(np.min(prcp)))
    print("     valeur max. = {:.2f} cm".format(np.max(prcp)))
    print("  quantile à 25% = {:.2f} cm".format(np.percentile(prcp, 25)))
    print("  quantile à 75% = {:.2f} cm".format(np.percentile(prcp, 75)))
    print("\n")

    print("Température minimale:")
    print("  valeur moyenne = {:.2f} °C".format(np.mean(Tmin)))
    print("  valeur médiane = {:.2f} °C".format(np.median(Tmin)))
    print("      écart type = {:.2f} °C".format(np.std(Tmin)))
    print("     valeur min. = {:.2f} °C".format(np.min(Tmin)))
    print("     valeur max. = {:.2f} °C".format(np.max(Tmin)))
    print("  quantile à 25% = {:.2f} °C".format(np.percentile(Tmin, 25)))
    print("  quantile à 75% = {:.2f} °C".format(np.percentile(Tmin, 75)))
    print("\n")

    print("Température maximale:")
    print("  valeur moyenne = {:.2f} °C".format(np.mean(Tmax)))
    print("  valeur médiane = {:.2f} °C".format(np.median(Tmax)))
    print("      écart type = {:.2f} °C".format(np.std(Tmax)))
    print("     valeur min. = {:.2f} °C".format(np.min(Tmax)))
    print("     valeur max. = {:.2f} °C".format(np.max(Tmax)))
    print("  quantile à 25% = {:.2f} °C".format(np.percentile(Tmax, 25)))
    print("  quantile à 75% = {:.2f} °C".format(np.percentile(Tmax, 75)))
    print("\n")


print("- Valeurs annuelles")
print_report(prcp, Tmin, Tmax)

- Valeurs annuelles
Hauteur des précipitations:
  valeur moyenne = 0.34 cm
  valeur médiane = 0.00 cm
      écart type = 0.68 cm
     valeur min. = 0.00 cm
     valeur max. = 4.67 cm
  quantile à 25% = 0.00 cm
  quantile à 75% = 0.36 cm


Température minimale:
  valeur moyenne = 8.66 °C
  valeur médiane = 9.40 °C
      écart type = 4.97 °C
     valeur min. = -6.00 °C
     valeur max. = 17.80 °C
  quantile à 25% = 5.60 °C
  quantile à 75% = 12.80 °C


Température maximale:
  valeur moyenne = 17.00 °C
  valeur médiane = 16.10 °C
      écart type = 7.26 °C
     valeur min. = -1.60 °C
     valeur max. = 35.60 °C
  quantile à 25% = 11.10 °C
  quantile à 75% = 22.20 °C




- Afficher les valeurs ci-dessus pour la période estivale

In [12]:
print("- Valeurs estivales")
summer = (day > 20140401) & (day < 20140930)
print_report(prcp[summer], Tmin[summer], Tmax[summer])

- Valeurs estivales
Hauteur des précipitations:
  valeur moyenne = 0.18 cm
  valeur médiane = 0.00 cm
      écart type = 0.48 cm
     valeur min. = 0.00 cm
     valeur max. = 3.33 cm
  quantile à 25% = 0.00 cm
  quantile à 75% = 0.03 cm


Température minimale:
  valeur moyenne = 11.92 °C
  valeur médiane = 12.80 °C
      écart type = 3.13 °C
     valeur min. = 4.40 °C
     valeur max. = 17.80 °C
  quantile à 25% = 10.00 °C
  quantile à 75% = 14.40 °C


Température maximale:
  valeur moyenne = 22.32 °C
  valeur médiane = 22.20 °C
      écart type = 5.43 °C
     valeur min. = 11.10 °C
     valeur max. = 35.60 °C
  quantile à 25% = 18.90 °C
  quantile à 75% = 26.10 °C




- Calculer la hauteur totale d'eau tombée à Seattle en 2014

In [13]:
print("Hauteur totale d'eau en 2014 : {} cm".format(np.sum(prcp)))

Hauteur totale d'eau en 2014 : 123.28 cm


- Dénombrer le nombre total de jours dans l'année pendant lesquels il a plu à Seattle et déterminer combien de ces jours étaient pairs

In [14]:
print("Nombre de jours pairs avec pluie : {}".format(np.sum((prcp > 0) & (day % 2 == 0))))

Nombre de jours pairs avec pluie : 71
